### ISSUE TITLE
How to build/run on OSX/Linux

### ISSUE THREAD

**Issue by vemv** [MSandeep96/SoundKeys#1]
Hey!

Project looking interesting.

How do I build/run this on Mac or Linux? Should be easy given the Electron framework.

Cheers - Victor

**Comment by MSandeep96** [comment]
Hey @vemv !
I've added the instructions to the README. 
I haven't personally tested it on OSX or Linux. The build instructions are the same though. 
Let me know if there's an error.

Thanks.

**Comment by vemv** [comment]
It builds/runs!

But after I launch it and login, I see SC itself and not the app:

![image](https://cloud.githubusercontent.com/assets/1162994/24832298/475c895c-1cad-11e7-903a-e74d6151944f.png)

If I restart the app, I won't require login again, but again I am shown SC itself - not SoundKeys.

Cheers - Victor

**Comment by MSandeep96** [comment]
That's exactly what SoundKeys is, Soundcloud wrapped in Electron. You get all the shortcuts mentioned and Notifications on top of SoundCloud. I didn't use the API as SoundCloud restricts caching on the API and there are no such restrictions on the web version. We can still get any view we want by DOM manipulation. A minimal interface is on the Roadmap though.

**Comment by vemv** [comment]
Ah, silly me! I assumed this was built on top of the SC API.

Still, it's a good idea! And the media keys sure work on my Mac! :)

Will recommend to a friend.
