### ISSUE TITLE
Bug #1 in Linux

### ISSUE THREAD

**Issue by aayushgupta1** [MSandeep96/SoundKeys#3]
Description :
**A JavaScript error occurred in the main process**
Uncaught Exception:
TypeError: Cannot read property 'isDestoryed' of undefined
      at App.app.on (/home/asikomov/SoundKeys/main.js:20:10)
      at emitOne (events.js:101:20)
      at App.emit (events.js:188:7)

This happens when I close the app using the close button(cross button) on the top left corner in linux(ubuntu).

**Comment by MSandeep96** [comment]
Tray features were built with Windows in mind. Support for linux will come shortly. Tab tak windows use kar.
