### ISSUE TITLE
No mini player

### ISSUE THREAD

**Issue by TraceyK14** [MSandeep96/SoundKeys#4]
The double down arrow button, which I'm assuming you click when you want the mini player, doesn't do anything. Windows 10. I didn't build it I installed it.

**Comment by MSandeep96** [comment]
Hey, I'm aware of that issue. I'll be releasing an update in some time which addresses that and has redesigned notifications. ETA: 2 weeks. I'll notify you when it's available.
[[UPDATE]] They changed the site's html. My scraping doesn't work anymore. Updating that part.

**Comment by MSandeep96** [comment]
Fixed. Will be releasing soon.

**Comment by TraceyK14** [comment]
@MSandeep96 Awesome! Sorry about not replying sooner. I will update when I get home and check it out. If you have it released by then

**Comment by MSandeep96** [comment]
Will take time. Have to implement notifications and automatic updates. There's a hacktober issue if you'd like to contribute.

**Comment by TraceyK14** [comment]
Ahh gotcha, no worries. And nice I'll check it out and see if  I can do anything with it.
