### ISSUE TITLE
[Help Wanted] Update design of miniPlayer

### ISSUE THREAD

**Issue by MSandeep96** [MSandeep96/SoundKeys#5]
The [mini player design](https://github.com/MSandeep96/SoundKeys/blob/master/ReadmeImages/miniPlayer.PNG) could use a touch up. The resources in use are located [here](https://github.com/MSandeep96/SoundKeys/tree/master/src/miniPlayerWindow).
Feel free to move away from FontAwesome. Put additional resources in assets.

Refer [CONTRIBUTING](https://github.com/MSandeep96/SoundKeys/blob/master/CONTRIBUTING.md) and [README.md](https://github.com/MSandeep96/SoundKeys/blob/master/README.md) to get started.
Comment if you need other help.

**Comment by TraceyK14** [comment]
How do you feel about moving to [Material Icons](https://material.io/icons/)?
