### ISSUE TITLE
Exception Thrown

### ISSUE THREAD

**Issue by srashee** [MSandeep96/SoundKeys#7]
OS: Arch Linux
WM: i3-wm

Building from source using your instructions i get the following error.

![image](https://user-images.githubusercontent.com/28571262/47238413-bbe2c400-d3a7-11e8-8c11-868b28f1723c.png)

**Comment by voldemar-bl** [comment]
> 
> 
> OS: Arch Linux
> WM: i3-wm
> 
> Building from source using your instructions i get the following error.
> 
> ![image](https://user-images.githubusercontent.com/28571262/47238413-bbe2c400-d3a7-11e8-8c11-868b28f1723c.png)

https://github.com/voldemar-bl/SoundKeys/releases

**Comment by srashee** [comment]
@voldemar-bl Thanks will give latest release a try tomorrow.

**Comment by MSandeep96** [comment]
Hi @srashee ,
There hasn't been an update. I haven't worked on this project in a long time.
